### ISSUE TITLE
main.cf needs extra settings to prevent emails being flagged insecure

### ISSUE THREAD

**Issue by John-B** [geerlingguy/ansible-role-postfix#4]
Gmail flags emails from postfix as 'sent insecurely.' On a production site, clients may object to this. 

The fix is to add lines to /etc/postfix/main.cf (path in Debian):
`smtpd_tls_security_level = may`
`smtp_tls_security_level = may`
`smtp_tls_loglevel = 1`
`smtpd_tls_loglevel = 1`

I found the fix at http://blog.snapdragon.cc/2013/07/07/setting-postfix-to-encrypt-all-traffic-when-talking-to-other-mailservers/, have tested it, and use it in production. It would be useful if this ansible role updates main.cf accordingly.

EDIT- Not tested on current version of postfix on Debian Stretch, where this role anyway bails out because a default apt-get install postfix no longer creates a main.cnf--if you want one it must be made manually.

**Comment by techdaddies-kevin** [comment]
Seconding this issue, we just got bit by it today.
